# Generated by Django 4.2.4 on 2023-08-29 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talleres',
            name='calidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='talleres',
            name='cp',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Ingresa un número válido de 5 dígitos.', regex='^\\d{5}$')]),
        ),
    ]
