# Generated by Django 4.2.4 on 2023-08-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_talleres_calidad_alter_talleres_cp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
