# Generated by Django 4.2.4 on 2023-09-25 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_clientes_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Solo se permiten letras y espacios.')])),
                ('cp', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Ingresa un número válido de 5 dígitos.', regex='^\\d{5}$')])),
                ('direccion', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Ingresa un número válido de 10 dígitos.', regex='^\\d{10}$')])),
                ('correo', models.EmailField(max_length=200)),
                ('contrasena', models.CharField(max_length=128)),
                ('calidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Talleres',
        ),
    ]
