# Generated by Django 4.2.4 on 2023-09-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_extendeddata_delete_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeddata',
            name='user',
        ),
    ]
