# Generated by Django 4.2.4 on 2023-09-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_extendeddata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeddata',
            name='cp',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='extendeddata',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
