# Generated by Django 4.2.4 on 2023-09-25 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0007_alter_extendeddata_cp_alter_extendeddata_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeddata',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
