# Generated by Django 4.2.4 on 2023-09-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_extendeddata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeddata',
            name='cp',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='extendeddata',
            name='direccion',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='extendeddata',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
