# Generated by Django 4.2.4 on 2023-09-26 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0010_alter_extendeddata_calidad_alter_extendeddata_cp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('bicicleta', 'Bicicleta'), ('moto', 'Moto')], max_length=10)),
                ('modelo', models.CharField(blank=True, max_length=10, null=True)),
                ('año', models.IntegerField(blank=True, default=0, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
