# Generated by Django 4.2.4 on 2023-09-26 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0011_vehiculos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mantenimiento y cambio de aceite', 'Mantenimiento y Cambio de Aceite'), ('frenos y sistemas de frenado', 'Frenos y Sistemas de Frenado'), ('alineación y balanceo de ruedas', 'Alineación y Balanceo de Ruedas'), ('sistema de escape', 'Sistema de Escape'), ('sistema eléctrico y electrónico', 'Sistema Eléctrico y Electrónico'), ('reparaciones de suspensión y amortiguación', 'Reparaciones de Suspensión y Amortiguación')], max_length=50)),
                ('tiempo', models.CharField(choices=[('1 hora', '1 hora'), ('2 horas', '2 horas'), ('3 horas', '3 horas'), ('4 horas', '4 horas'), ('Más de 5 horas', 'Más de 5 horas')], max_length=50)),
                ('precio', models.IntegerField(choices=[('$300 - $1,000', '$300 - $1,000'), ('$1,000', '$1,000'), ('$2,000', '$2,000'), ('$3,000', '$3,000'), ('$4,000', '$4,000'), ('$5,000 - $10,000', '$5,000 - $10,000'), ('$11,000 - $15,000', '$11,000 - $15,000'), ('Más de $16,000', 'Más de $16,000')], max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
